apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: back-api
          image: redis:7.0.2-alpine
          ports:
            - containerPort: 6379
              name: redis
          env:
            - name: CC_DB_PASS
              valueFrom:
                secretKeyRef:
                  key: CC_DB_PASS
                  name: my-secret
          command: [ "redis-server" ]
          args: [ "--requirepass", $(CC_DB_PASS) ]
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: my-pvc