version: "3.8"
services:
  server:
    build: ./
    ports:
      - "5000:5000"
    environment:
      CC_SERVER_PORT: 5000
      CC_SERVER_ADDRESS: http://127.0.0.1
      CC_DB_ADDRESS: postgres://ccapp@postgres/ccdb
      CC_DB_USERNAME: ccapp
      CC_DB_PASSWORD: password
      CC_EXPIRATION: 2
  db:
    image: postgres:alpine3.16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ccapp
      POSTGRES_DB: ccdb
    volumes:
      - ccdbvol:/var/lib/postgresql/data
volumes:
  ccdbvol:
#    driver: local