version: "3.8"
services:
  server:
    build: ./
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
    ports:
      - "5000:5000"
    environment:
      CC_SERVER_PORT: 5000
      CC_SERVER_ADDRESS: http://127.0.0.1
#      CC_DB_ADDRESS: postgres://ccapp@postgres/ccdb
      CC_DB_ADDRESS: 10.5.0.5
      CC_DB_NAME: ccdb
      CC_DB_USER: ccapp
      CC_DB_PASS: password
      CC_EXPIRATION: 2
    depends_on:
      - db
  db:
    image: postgres:alpine3.16
    restart: always
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ccapp
      POSTGRES_DB: ccdb
      POSTGRES_PASSWORD: password
    volumes:
      - ccdbvol:/var/lib/postgresql/data
volumes:
  ccdbvol:
#    driver: local
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1